### PR TITLE
py/persistentcode: Use a .mpy format that's backwards compatible

### PR DESCRIPTION
**Pull request by aykevl**
This is a slightly different file format, compatible with current .mpy files (previously this branch would break compatibility). Also fixed build errors related to the file format, so it actually builds now.

Tested with the modx example, it works.

### CODE REVIEW

**Comment by dpgeorge** [comment]
> This is a slightly different file format, compatible with current .mpy files (previously this branch would break compatibility)

The idea with the way I did it was so there could be both bytecode and native code in the one .mpy file.  That's for two reasons:
1. Use of @micropython.native/viper/asm_thumb decorators in a given script can mean that that script will have a mix of bytecode and native code.
2. Opens the possibility to create a .mpy file that has speed-critical code in native machine code and the rest of the module written in Python, ie bytecode.

> Also fixed build errors related to the file format, so it actually builds now.

I'm pretty sure I tested it before pushing... what were the errors exactly?

**Comment by aykevl** [comment]
Oh, asm etc isn't possible right now? I kind of assumed it was. Then it makes sense to include them as well. It would be nice (I think) to keep compatibility, though. I can take a look to see whether it's possible. Being able to include both native code and bytecode would also be nice, hadn't thought of that before.
I do think the version should be incremented when creating incompatible files, though.

IIRC the errors were in mpy-tool.py. I can take a look when I get home.

**Comment by dpgeorge** [comment]
> Oh, asm etc isn't possible right now? I kind of assumed it was.

If they were possible then the issue of putting native code into mpy files would be solved, and we could already put compiled C code in them :)

> It would be nice (I think) to keep compatibility, though. I can take a look to see whether it's possible.

One way is to have a new flag in the existing 4-byte header that indicates if the mpy is pure bytecode or a mix, and if it's a mix then each function that is loaded must have a type associated with it.  But this complicates the mpy loader.

> I do think the version should be incremented when creating incompatible files, though.

Yes, the version number would increase when native code capability is added, so it's OK to modify the mpy format.

**Comment by aykevl** [comment]
Steps to reproduce:

1. `make clean` in mpy-cross
2. `make clean` in ports/unix
3. `make axtls`
4. `make`

result (maybe different from what I first got as error):

```
[snip]
CC ../py/../lib/utils/printf.c
CC main.c
CC gccollect.c
LINK mpy-cross
   text	   data	    bss	    dec	    hex	filename
 141387	  14472	    872	 156731	  2643b	mpy-cross
make[1]: Leaving directory '/home/ayke/src/micropython/mpy-cross'
MPY modules/upip.py
MPY modules/upip_utarfile.py
Creating build/frozen_mpy.c
Traceback (most recent call last):
  File "../../tools/mpy-tool.py", line 596, in <module>
    main()
  File "../../tools/mpy-tool.py", line 584, in main
    raw_codes = [read_mpy(file) for file in args.files]
  File "../../tools/mpy-tool.py", line 456, in read_mpy
    return read_raw_code(f)
  File "../../tools/mpy-tool.py", line 431, in read_raw_code
    raise Exception('unsupported code type: %u' % code_type)
TypeError: %u format: a number is required, not str
../../py/mkrules.mk:121: recipe for target 'build/frozen_mpy.c' failed
make: *** [build/frozen_mpy.c] Error 1
make: *** Deleting file 'build/frozen_mpy.c'
```

(closed the pull request as this isn't about the pull request)

**Comment by dpgeorge** [comment]
@aykevl the build error was due to Python 2 being used instead of Python 3 which is why I didn't see it initially.  Fixed in b19c51c0e1e58c7d18ce7b5eaadd4accf24074fd

**Pull request closed without merging**
