### PR TITLE
F7disc sdram enabled

### PR DESCRIPTION
**Pull request by forester3**
I try to work SDRAM on STM32F746G-Discovery.
It seems work well.
It takes about 27 ms to copy 1Mbyte.
It takes about １１５ ms to copy ２Mbyte.
System clock is downed to 192MHz to work SDRAM, and add MPU config.
I am not sure of 429 I-disco change in mpconfigboard.h.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for this, it's great you got it working!

> System clock is downed to 192MHz to work SDRAM

Was this a necessary change?  Instead of this, would it be possible to modify the SDRAM timings so it can work with a 216MHz CPU frequency?

> add MPU config.

Note that (as far as I know) it's only possible to configure the MPU once, it only has the ability to configure one region of memory.  So it will be the last MPU setting that has any effect.

Finally, could you please re-post this as a PR to the main repository at https://github.com/micropython/micropython?  Then it can be (eventually) merged there.

**Comment by forester3** [comment]
Thanks for your responce.


I heard that it is necessary to set systemclock to 200 MHz or less to operate SDRAM.
It is in Japanese enginner's blog.(only in Japanese)


About MPU reagion, I think that we can set multiple MPU region. I have seen samples that are set in 4 regions in STMicro's sample.
The MPU setting in the RAM area has an effect. When setting is not done, it takes 40 ms to copy 1 MByte.


Since there was a clock down issue, I refrained to pull request to the micropython / micropython repository.
If there is no problem, I will redo the PR.


----- Original Message -----

**Comment by forester3** [comment]
I found MPU reasion sample again. It will be found here:
https://www.st.com/content/ccc/resource/technical/document/application_note/group0/25/ca/f9/b4/ae/fc/4e/1e/DM00287603/files/DM00287603.pdf/jcr:content/translations/en.DM00287603.pdf

**Comment by dpgeorge** [comment]
> I heard that it is necessary to set systemclock to 200 MHz or less to operate SDRAM.

Yes you are right.  In the data sheet (for STM32F767) it says that FMC_SDCLK must be 100MHz or less.  And FMC_SDCLK=HCLK/2, so that limits the HCLK to 200MHz.

> About MPU reagion, I think that we can set multiple MPU region.

Yes you're right.  You can set up to 8 regions at a time, using the region number.

> The MPU setting in the RAM area has an effect. When setting is not done, it takes 40 ms to copy 1 MByte.

But I see that you are configuring the MPU region 0 for the internal SRAM.  Why is this needed?  I would think that the internal SRAM should not need any MPU.

> Since there was a clock down issue, I refrained to pull request to the micropython / micropython repository.

Ok, I see.  Since this STM32F7DISC board is used as an example to show how to configure MicroPython, I think it is fair enough to reduce the clock speed and enable the SDRAM.  We can add a note in the mpconfigboard.h file that the clock can be put to 216MHz if SDRAM is enabled.

**Comment by forester3** [comment]
I am not good at English,and I do not understand this document all.
https://www.st.com/content/ccc/resource/technical/document/application_note/group0/bc/2d/f7/bd/fb/3f/48/47/DM00272912/files/DM00272912.pdf/jcr:content/translations/en.DM00272912.pdf

Since F7mpu has two kinds of RAM areas, I think that such MPU area setting is effective.

**Comment by dpgeorge** [comment]
This was merged upstream, see https://github.com/micropython/micropython/pull/4032

**Pull request closed without merging**
