### PR TITLE
stm32-h7b3-support branch additions

### PR DESCRIPTION
**Pull request by JohnieBraaf**
I've mapped and tested the SDCard and UART4 for this board.
They work fine. I've not bee able to get flash working, yet.
Did you have it working before? It should be identical to the STM32H743 in addressing.

### CODE REVIEW

**Comment by JohnieBraaf** [comment]
As a note, the board only works when I have ran a STM32Cube project before, then flash micropython and pressing the reset button.
This produces the REPL. When the board is powered off and back on it does not seem to boot.

**Comment by JohnieBraaf** [comment]
On a second note, it does seem that enabling the flash does not seem to be straightforward as it would require implementing a Octo-SPI driver of some sort. [AN5050](https://www.st.com/resource/en/application_note/dm00407776-octospi-interface-on-stm32-microcontrollers-stmicroelectronics.pdf)

**Comment by JohnieBraaf** [comment]
Fixed bootup of board with:

` MODIFY_REG (PWR->CR3, PWR_SUPPLY_CONFIG_MASK, PWR_CR3_SMPSEN);`

**Comment by JohnieBraaf** [comment]
- Bootup of microcontroller fixed (powerctrl.c)
- STM32lib stm32h7b3xxq.h does not define USB_OTG_FS, so usb_conf.c has been slightly altered to accomodate for this case

**Comment by JohnieBraaf** [comment]
@dpgeorge, did you find a way to get the Octo-SPI flash and memory mapping working? From what I can tell there is no driver provision for this in drivers/memory/spiflash

https://github.com/dpgeorge/micropython/blob/stm32-h7b3-support/drivers/memory/spiflash.h#L34-L37

**Comment by JohnieBraaf** [comment]
Sample project by ST: [MX25LM51245G_STM32H7B3I-DISCO](https://github.com/STMicroelectronics/stm32-external-loader/tree/main/STM32H7x_boards/MX25LM51245G_STM32H7B3I-DISCO)

**Comment by JohnieBraaf** [comment]
This board has 2 OCTO SPI interfaces, I think the current setup like in qspi.c will not work as it supports  only a single interface.
E.g QUADSPI->CR would need to be either OCTOSPI1->CR or OCTOSPI2->CR
I think the interface needs to be abstracted somehow.

**Comment by JohnieBraaf** [comment]
This user has already tested octo spi for spi memory with micropython: [micropython-spiram](https://github.com/koendv/micropython-spiram)

**Comment by JohnieBraaf** [comment]
Hi @dpgeorge, I've corrected a number of things for this board in your working branch, I hope it helps towards implementing support for this board. 

I still cannot get (internal) flash and usb MSC to work, I have no clue how to pursue this further.

**Please advice if you would like to see a PR upstream for the work so far.** 

I think the aim should be to enable the following MCU's at once as they share the same properties:
-STM32H7A3xx
-STM32H7A3xxQ
-STM32H7B3xx
-STM32H7B3xxQ

**Comment by dpgeorge** [comment]
Thank you very much, this is great work!  Especially the `MODIFY_REG(PWR->CR3, PWR_SUPPLY_CONFIG_MASK, PWR_CR3_SMPSEN);` addition, I completely missed that and it explains some of the issues I was seeing.

> Please advice if you would like to see a PR upstream for the work so far.

Yes I definitely want to get this upstream, it's just a matter of how to coordinate it and if you want to retain authorship on your work. 

If you want to do the work, I'm happy for you to just take my H7B3 branch here and use it as the basis for your own branch which has all these changes in this PR, and then you can submit it upstream as a PR.  I don't need to have myself as the author, you can squash it all down to one commit that you author (but maybe credit me in the commit message :).  Then I can test it on the H7B3 DK that I have (I already broke one of these somehow...).

**Comment by JohnieBraaf** [comment]
Ok, sure I will create a squashed upstream PR, while trying to presrve your authorship.

It turns out that only the Q version of these MCU's have the PWR_CR3_SMPSEN option:
- stm32h7a3xxq
- stm32h7b3xxq

I will modify the logic accordingly and go over everything one more time.

By the way, you mention you have broken one of your boards. 
There is a special restore procedure involving the swith left of the screen (page 18 of [UM2569](https://www.st.com/resource/en/user_manual/dm00610478-discovery-kit-with-stm32h7b3li-mcu-stmicroelectronics.pdf))

```
If a deadlock is faced due to a mismatch between the hardware board setting and the firmware
setting (LDO/SMPS), the user can recover the board by doing the following:
• Power off the board.
• Change the SW1 switch position to "1".
• This changes the BOOT0 pin to 1 instead of 0 and thus the device boot address is changed
to boot address 1 making the bootloader starting in System memory, instead of starting the
firmware in the user Flash (Firmware that is setting a wrong LDO/SMPS configuration).
• Power on the board, and connect using STM32CubeProgrammer.
• Erase the user Flash.
• Power off the board and put back the switch SW1 to position "0".
• The board is now recovered and can proceed normally. 
```

**Comment by JohnieBraaf** [comment]
Ai, I messed up my repository, Im closing this PR and will recreate upstream
For reference this was the state before messing up: https://github.com/JohnieBraaf/micropython/commits/c4f4cb14a455c7dfbe81d18265b9cfb718d265f0

**Pull request closed without merging**
